### ISSUE TITLE
Not accessible at all

### ISSUE THREAD

**Issue by jmuheim** [kazzkiq/balloon.css#19]
Neither keyboard only users nor screenreader users will ever be able to perceive these tooltips. A pity.

**Comment by sbible** [comment]
Keyboard support can be easily added using :focus.

**Comment by kazzkiq** [comment]
@jmuheim For screenreaders, a good technique would be appending a hidden element with the same content of the tooltip inside the tooltip elements.

As Balloon.css do not use JavaScript, you cannot achieve it with this library alone. However this can be easily achieved with a little bit of JavaScript and CSS on your project:

``` js
// Append a span with tooltip text to all elements containing tooltips

var tooltips = document.querySelectorAll('[data-balloon]');

tooltips.forEach(function (tooltip) {
    var span = document.createElement('SPAN');
    span.setAttribute('class', 'hide-me');
    span.innerHTML = tooltip.getAttribute('data-balloon');
    tooltip.appendChild(span);
});
```

``` css
/* make the span invisible to non-screenreaders */

[data-balloon] span.hide-me {
    position:absolute;
    width: 1px;
    height: 1px;
    overflow: hidden;
}
```
