### ISSUE TITLE
Is that possible to support render html element in balloon?

### ISSUE THREAD

**Issue by slimsymphony** [kazzkiq/balloon.css#22]
Or just provide some ways to control the line break. 
Thanks.

**Comment by kazzkiq** [comment]
@slimsymphony For now, Balloon.css do not support manual line breaking, however you can force it with just some lines of CSS. Example:

``` html
<!-- For line breaking, use the special charecter: &#10; -->
<button data-balloon="Line One &#10; Line Two" data-balloon-pos="up" data-balloon-break>Hover me!</button>
```

``` css
[data-balloon][data-balloon-break]::before {
    white-space: pre-wrap;
}
```

You can see a live example here: https://jsfiddle.net/7d6n63r4/
