### ISSUE TITLE
data-balloon-length="fit" tooltip broken

### ISSUE THREAD

**Issue by Qiplex** [kazzkiq/balloon.css#94]
Hello,

I'm trying to fit ballon text in the tooltip. Since text-length varies I need the tooltip to auto-expand or shrink based on text length.

I've tried to use `fit` as `data-ballon-length`: 

```html
data-balloon="${dirnameSpaceSlash}" data-balloon-length="fit"  data-balloon-pos="left"
```
But the tooltip seems to be broken 

<img width="425" alt="screen shot 2018-02-14 at 14 17 21" src="https://user-images.githubusercontent.com/32670415/36204049-68486d22-1192-11e8-94a0-a4f663c18769.png">

There is no issues with `data-ballon-length` like `large`, `medium`, `small` with fixed width in `px` but only with `fit` which width is `100%` 

```css
  [data-balloon][data-balloon-length='fit']:after {
    white-space: normal;
    width: 100%; }
```
```css
[data-balloon][data-balloon-length='small']:after {
    white-space: normal;
    width: 80px; }
  [data-balloon][data-balloon-length='medium']:after {
    white-space: normal;
    width: 150px; }
  [data-balloon][data-balloon-length='large']:after {
    white-space: normal;
    width: 260px; }
  [data-balloon][data-balloon-length='xlarge']:after {
    white-space: normal;
    width: 380px; }
```

Thanks!

**Comment by kazzkiq** [comment]
The `fit` in `data-balloon-length` refers to the element width. So, if your element has small width, the tooltip will also assume this small width. This is probably what is causing your tooltip to be so narrow and break in so many lines.

I guess in this case you would be forced to use one of the default values (`small`, `medium`, `large` or `xlarge`) which use `px`. Or you can create another one for your purpose by adding something like this CSS into your project:

```css
[data-balloon][data-balloon-length='my-personal-length']:after {
  white-space: normal;
  width: 123px; /* Your personal width */
}
```
